# eks ecr fargate hpa manifest
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eks-ms-hpa
  namespace:  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eks-ms-hpa
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
          